name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bazelisk
        run: |
          curl -fsSLO https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
          chmod +x bazelisk-linux-amd64
          sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Bazel tests
        run: bazel test //...

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bazel-test-logs
          path: bazel-out/
          retention-days: 5
